---

- name: Install pip package
  apt: name=python-pip state=present
  register: pip_installed

- name: Install required python packages
  when: pip_installed | success
  pip: name="{{ item.package }}" version="{{ item.version }}"
  with_items: "{{ required_packages }}"
  register: required_packages_installed

- name: Make sure {{ ast_path }} exists
  file: path={{ ast_path }} state=directory mode=0600
  register: makesnapshots_folder_exists

- name: Setup backup scripts
  when: (makesnapshots_folder_exists | success) and (required_packages_installed | success)
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0700
  with_items:
    - { src: config.j2 , dest: "{{ ast_path }}/config.py" }
    - { src: makesnapshots.py.j2 , dest: "{{ ast_path }}/makesnapshots.py" }

- name: Setting cron to run daily into /etc/cron.d
  cron: |
    name="Daily EBS EC2 Volume snapshot"
    job="{{ ast_path }}/makesnapshots.py day"
    cron_file="aws-snapshot-daily"
    user=root state=present
    minute=30 hour=1 weekday="1-5"

# # Weekly EBS EC2 Volume snapshot
# 30 2 * * 6 {{ ast__user }} {{ ast_path }}/makesnapshots.py week

# # Monthly EBS EC2 Volume snapshot
# 30 3 1 * * {{ ast__user }} {{ ast_path }}/makesnapshots.py month

#- debug: msg="{{ auto_update }}"
